version: '3.8'

services:
  db:
    image: postgres:15.2
    container_name: bank_mock
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bank_mock
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"


volumes:
  postgres_data: